name: py5
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8=2.0.*
  - black=23.3.*
  - cairo=1.16.*
  - cairocffi=1.5.*
  - cairosvg=2.6.*
  - flake8=6.0.*
  - hatch=1.7.*
  - ipykernel>=6.29.5
  - ipython=8.12.*
  - jedi=0.18.2
  - jpype1=1.4.*
  - jupyter=1.0.*
  - jupyter-book=0.15.1
  - jupyter-packaging=0.12.*
  - jupyterlab=4.0.*
  - jupytext=1.14.7
  - line_profiler=4.0.*
  - matplotlib=3.7.*
  - nodejs=18.15.*
  - numpy=1.24.*
  - pandas=2.0.*
  - pillow=9.5.*
  - pip
  - python=3.8.*
  - requests=2.29.*
  - shapely=2.0.*
  - trimesh=3.23.*
  - twine=4.0.*
  - yarn=1.22.*
  - pip:
    - bump2version==1.0.*
    - stackprinter==0.2.*
